Bookstore/.w/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import Rate
from . import app_settings


urlpatterns = [
    url(r'(?P<content_type_id>\d+)/(?P<object_id>' + app_settings.STAR_RATINGS_OBJECT_ID_PATTERN + ')/', Rate.as_view(), name='rate'),
]

app_name = 'star_ratings'

Bookstore/Bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from myCart import urls
from homepage import urls
from BookDetails import urls
from products import urls

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', include('homepage.urls')),        
    path('myCart/', include('myCart.urls')),
    path('BookDetails/', include('BookDetails.urls')),
    path('homepage/', include('homepage.urls')),
    path('products/', include('products.urls')),
    path('prof/', include('prof.urls')),
    path('profile/', include('prof.urls'))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bookstore/homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"
urlpatterns = [    
    path('', views.index, name='index'), 
]

Bookstore/myCart/urls.py
from django.urls import path
from . import views

app_name = "myCart"
urlpatterns = [
    path('', views.index, name='index'),
    path('myCart/', views.index, name="myCart"),
    path('changeQuantity/', views.cart_quantity_change, name="changeQuantity"),
    path('removeCartItem/', views.cart_item_remove, name = "removeCartItem"),
    path('deleteSFLitem/', views.delete_SFL_item, name = "delete_SFL_item"),
    path('moveCartItemToSFL/', views.move_cart_item_to_SFL, name = "moveCartItemToSFL"),
    path('moveSflToCart/', views.move_sfl_item_to_cart, name="moveSflToCart"),
    path('addItem/', views.add_item, name ="add_item"),
    path('checkout/', views.checkout, name = "checkout"),
    path('confirm_checkout/', views.confirm_checkout, name = "confirm_checkout"),



    #Views for TESTING. IGNORE THESE
    path('createCookieTest/', views.createCookieTest, name="createCookieTest"),
    path('cookieInfo/', views.cookieInfo, name='cookieInfo'),
    path('makeCartCookie/', views.makeCartCookie, name='makeCartCookie'),
    #path('login_page/', views.login_page, name="loginpage"),
    path('homepage/', views.homepage, name="homepage"),
    path('testView1/', views.testView1, name="testView1"),
    path('sessionTest/', views.sessionTest, name="sessionTest"),
    #path('index', views.index2, name = 'index2')
]

Bookstore/prof/urls.py
from django.urls import path
from . import views

app_name = 'prof'
urlpatterns = [
    path ('profileInfo/', views.profileInfo, name = 'profileInfo'),
    path('register/', views.RegistrationView, name = 'register'),
    path('login/', views.user_login, name = 'login'),
    path('login/error/', views.user_login, name = 'login_error'),
    path('change_password/', views.change_password, name ="change_password"),
    path('logout/', views.user_logout, name = 'logout'),
    path('add_reserved_card/', views.add_reserved_card, name = "add_reserved_card"),
    path('add_preferred_card/', views.add_preferred_card, name = "add_preferred_card"),
    path('add_address/', views.add_shipping_address, name = "add_shipping_address"),
    path('modify_password/', views.modify_password, name ="modify_password")
]

Bookstore/homepage/models.py
from django.db import models

Bookstore/myCart/models.py
from django.db import models

# Create your models here.

Bookstore/myCart/forms.py
from django import forms


class QuantityChangeForm(forms.Form):
    New_quantity = forms.IntegerField()
    Cart_contentID = forms.CharField(widget = forms.HiddenInput)

class ItemRemoveForm(forms.Form):
    Cart_contentID = forms.CharField(widget = forms.HiddenInput)

#Form for deleting an item in the Save for later table
class DeleteSFLForm(forms.Form):
    Saved_ContentID = forms.CharField(widget = forms.HiddenInput)

class MoveCartItemToSFLForm(forms.Form):
    Cart_contentID = forms.CharField(widget = forms.HiddenInput)
    #Saved_contentID = forms.CharField(widget = forms.HiddenInput)

class MoveSflToCartForm(forms.Form):
    Saved_contentID = forms.CharField(widget = forms.HiddenInput)

class AddItemForm(forms.Form):
    ISBN = forms.CharField(widget = forms.HiddenInput)

Bookstore/homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return(render(request, 'homepage/index.html', {}))

Bookstore/myCart/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import loader
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse
from database.models import CART
from database.models import CART_CONTENT
from database.models import BOOK
from .forms import *
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required


from django.contrib.sessions.models import Session

from . import utility
#test
from django.contrib.auth.models import User
from database.models import USER, SAVED_FOR_LATER_CONTENT
def index(request):
    print("View [index] was called.")
    context = {}
    cart_id = ''
    
    if request.user.is_authenticated: #treat as logged in user
        print("User is logged in.")
        auth_user_id = request.user.id
        print("auth_user_id is: " + str(auth_user_id))
        print(type(auth_user_id)) 

        auth_user = User.objects.get(id = auth_user_id)
        user = USER.objects.get(AuthUser_ID = auth_user_id)

        cart_id = user.Cart_ID.Cart_ID
        saved_for_later_content_list = SAVED_FOR_LATER_CONTENT.objects.filter(ProfileID=user.ProfileID)
        print("saved_for_later_content_list: " + str(saved_for_later_content_list))

        cart = CART.objects.get(Cart_ID = cart_id)
        print("cart is: " + str(cart))

        cart_content_list = cart.cart_content_set.all()
        print("cart_content_list is: " + str(cart_content_list))

        context = {
            'cart_content_list': cart_content_list,
            'cart_content_list_length': len(cart_content_list),
            'Cart_ID': cart_id,
            'subtotal': utility.subtotal(cart),
            'saved_for_later_content_list': saved_for_later_content_list,
            'saved_for_later_content_list_length': len(saved_for_later_content_list),
            'form': forms.QuantityChangeForm(), #used to change quantity of an item
        }
        
        return render(request, 'myCart/index.html', context = context)

    else: #treat as anonymous user
        CART_COOKIE_NAME = 'CartID'
        if CART_COOKIE_NAME in request.COOKIES:            
            print(CART_COOKIE_NAME + " is a valid cookie name.")
            cart_cookie_value = request.COOKIES[CART_COOKIE_NAME]
            print("cart_cokie_value is: " + str(cart_cookie_value))

            print("call Z1")
            cart = CART.objects.all().get(Cart_ID = cart_cookie_value)
            print(cart)
            
            print("Creating cart_content_list")
            cart_content_list = cart.cart_content_set.all()

            print("Printing: CART_CONTENT.objects.filer(cart_id = cart_cookie_value)")
            print(CART_CONTENT.objects.filter(Cart_ID = cart_cookie_value))

            #DON'T FORGET TO DELETE THIS --- TESTT 
            #print("overriding cart and cart_content_list for testing")
            #cart = CART.objects.get(Cart_ID = 'RKV8igMqYPF5EE46bvSyTLQXQKwytyxh') #this cart id actually exists in DB
            #cart = CART.objects.get(Cart_ID = 'blimNAdztSuJWS4kn5NakPArzYIBW5gS')
            #print("Using CartID: RKV8igMqYPF5EE46bvSyTLQXQKwytyxh")
            #cart_content_list = cart.cart_content_set.all()
            #print("override cart_content_list: " +str(cart_content_list))
            #DON'T FORGET TO DELETE THIS --- TESTT
            
            context = {
                'cart_content_list': cart_content_list,
                'cart_content_list_length': len(cart_content_list),
                'Cart_ID': cart_cookie_value,
                'subtotal': utility.subtotal(cart),
                'saved_for_later_content_list': None, #None because saved for later feature is for logged in users only
                'saved_for_later_content_list_length': 0,
                'form': forms.QuantityChangeForm(), #used to change quantity of an item
            }
            
            print("subtotal is: " + str(utility.subtotal(cart)))
            
            return render(request, 'myCart/index.html', context = context) #convert to redirect?
        else:
            #The session does not contain a reference to a cart! Let's create a cart for the anonymous user.
            print("The " + CART_COOKIE_NAME + " was NOT found.")
            print("Creating a " + CART_COOKIE_NAME + " cookie...")
            
            cart_cookie_value = utility.generate_Cart_ID()
            cart = CART(Cart_ID = cart_cookie_value)
            cart.save()
            
            print("Done creating cookie.")
            
            
            #Take the visitor back to this same page. They should have a sessionid and cookie now
            #if user has cookies disabled, this could be infinite loop!
            response = HttpResponseRedirect(reverse("myCart:index", args=None))

            print("Setting the response cookie.")
            response.set_cookie(CART_COOKIE_NAME, cart_cookie_value)
            

            print("response.cookies is: " + str(response.cookies))
            
            return response

    return HttpResponse("Check CMD, something went wrong!")




from . import forms
from . import utility
#This index changes the quantity of a CART_CONTENT tuple
#The information on what tuple, and what the new quantity
# should be is specified in the POST information from the
# request.
def cart_quantity_change(request):
    print("Called [cart_quantity_change2] view")
    
    if request.method == "POST":
        form = forms.QuantityChangeForm(request.POST)

        print("checking if valid:")

        print(request.POST)

        if form.is_valid():
            print("form is valid")
            print("Printing form: " + str(form))
            cart_content_id = form.cleaned_data['Cart_contentID']
            new_quantity = form.cleaned_data['New_quantity']
            utility.change_cart_quantity(cart_content_id=cart_content_id, new_quantity=new_quantity) #use object or 404
            return HttpResponseRedirect(reverse('myCart:index', args=None))
        else:
            print("form is invalid")
            return Http404("Invalid form!")

    else:
        print("Not POST!")
        return Http404("Expected POST: request is not POST")

    return HttpResponse("Uhh read CMD")

#remove an item from a cart
from django.contrib.auth.models import User
from .forms import ItemRemoveForm
from database.models import CART_CONTENT
def cart_item_remove(request):
    print("View [cart_item_remove] called.")
    if request.method == "POST":
        print("Is POST")
        form = ItemRemoveForm(request.POST)
        print(request.POST)

        if form.is_valid():
            print("form is valid")
            print("Printing form: " + str(form))

            cart_content_id = form.cleaned_data['Cart_contentID']
            
            c = None
            try:
                #c = CART_CONTENT().objects.get(Cart_contentID=cart_content_id)
                c = CART_CONTENT.objects.get(Cart_contentID = cart_content_id)
            except CART_CONTENT.DoesNotExist:
                c = None
                raise Http404("Cart item does not exist!")

            print("deleting: " + str(c))
            c.delete()

            print("deleted successfully")
            
            return HttpResponseRedirect(reverse("myCart:index", args=None))
        else:
            print("The form to remove a content item was invalid.")
            raise Http404("The form to remove content item was invalid.")
    else:
        raise Http404("Request to remove cart item was not POST. Must be post and valid form.")
    


def delete_SFL_item(request):
    print("called view: [delete_SFL_item]")
    form = DeleteSFLForm(request.POST)
    print("form is: " + str(form))

    if form.is_valid():
        print("form is valid")
        Saved_ContentID = form.cleaned_data['Saved_ContentID']

        sfl = None
        try:
            sfl = SAVED_FOR_LATER_CONTENT.objects.get(Saved_ContentID = Saved_ContentID)
            print("sfl chosen for deletion is: " + str(sfl))
            sfl.delete()
        except SAVED_FOR_LATER_CONTENT.DoesNotExist:
            raise Http404("Can't delete this saved for later item because it doesn't exist")

        print("Saved for later item deleted")
        return HttpResponseRedirect(reverse("myCart:index", args=None))
    else:
        return HttpResponse("The form to delete a Saved For Later item was invalid!")


def move_cart_item_to_SFL(request):
    print("called view: [move_cart_item_to_SFL]")
    form = MoveCartItemToSFLForm(request.POST)
    print("form is: " + str(form))

    if form.is_valid():
        print("form is valid")
        Cart_contentID = form.cleaned_data['Cart_contentID']
        

        cc = None #user's cart content object to be transfered to saved for later
        user = None #user 
        sfl = None #saved for later object linked to the user

        try:
            cc = CART_CONTENT.objects.get(Cart_contentID = Cart_contentID)
        except CART_CONTENT.DoesNotExist:
            raise Http404("Can't move cart item because item doesn't exist")

        try:
            user = USER.objects.get(Cart_ID = cc.Cart_ID )
        except USER.DoesNotExist:
            raise Http404("Can't move cart item because can't find a link to a user from the Cart_contentID")
        
        try:
            sfl = SAVED_FOR_LATER_CONTENT(ProfileID = user, ISBN = cc.ISBN)
        except SAVED_FOR_LATER_CONTENT.DoesNotExist:
            raise Http404("Can't create a SAVED_FOR_LATER_CONTENT object")


        print("Saving sfl and deleting cc...")
        sfl.save()
        cc.delete()
        print("Done deleting and saving.")
       
        return HttpResponseRedirect(reverse("myCart:index", args=None))
    
    return HttpResponse("Invalid form input: <br>"+str(form.errors))
    

def move_sfl_item_to_cart(request):

Bookstore/templates/myCart/base.html
<!doctype html>
{% load static %} 
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <!-- Glyphicons by fontawesome.com -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <title>Geek Peek</title>
  </head>
  <body>      
   
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

            <!-- Brand -->
            <a class="navbar-brand" href="http://localhost:8000/">
                <img class="rounded-circle" src= "{% static "myCart/TemporaryLogo.jpg" %}" width="30" height="30" class="d-inline-block align-top" alt="">    
                Geek Peek
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                
                <!-- Home link -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                    <a class="nav-link" href="http://localhost:8000/">Home <span class="sr-only">(current)</span></a>
                    </li>                   
                </ul>

                <!-- Login/Register Button-->
                {% if user.is_authenticated %}
                    <span class="navbar-text mr-sm-2">
                        Hello, {{user.username}}
                    </span>
                {% else %}
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary">Register</button>
                        <button type="button" class="btn btn-primary">Login</button>                        
                    </div>
                {% endif %}
                
                <!-- Cart Button -->
                <a href="{% url 'index' %}" class="btn btn-warning">
                    <i class = "fa fa-shopping-cart"></i>
                    View Cart
                    <span class="badge" style="font-size:100%"></span> <!-- Static for now --> 
                </a>
                
                <!--Search Bar-->
                <form class="form-inline my-3 my-lg-0"> 
                    <input class="form-control mr-sm-2" type="search" placeholder="Book Search" aria-label="Search">
                    <button class="btn btn-success my-2 my-sm-0" type="submit">Search</button>
                </form>
                

                <!--View Profile-->
                {% if user.is_authenticated %}
                <button type="button" class="btn btn-primary disabled mr-sm-2">View Profile</button>
                {% endif %}

                <!-- Logout button (if user loged in)-->
                {% if user.is_authenticated %}
                    <span class="navbar-text mr-sm-2">
                            <button type="button" class="btn btn-danger">Log Out</button>  
                    </span>
                {% endif %}

            </div> <!--Collapse-->
        </nav> <!--Navigation bar-->
    
    
    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

Bookstore/templates/myCart/checkout.html
{% extends 'base.html' %}


{% block content %}

<div class = "container">
    <div class = "row">
    <div class = "col">
        {% if user.is_authenticated %} 
            <h1> Shipping address </h1>
            {% if default_address %}
                There is a shipping address<br>
                Address1: {{default_address.Address_1}} <br>
                Address2: {{default_address.Address_2}} <br>
                Country: {{default_address.Country}} <br>
                State: {{default_address.country}},
                City: {{default_address.City_Town}} <br>
                Name: {{default_address.Name}} <br>
                <a href = "{% url 'prof:add_shipping_address' %}">Click here to change shipping address</a>
                

            {% else %}
                There is no shipping address<br>
                <a href="{% url 'prof:add_shipping_address' %}"> Click here to add one</a>
            {% endif %}
            <hr>
        
            <h1> Payment method </h1>
            {% if default_credit_card %}
                First name: {{default_credit_card.Fname}} <br>
                Last name: {{default_credit_card.Lname}} <br>
                Expiration Month: {{default_credit_card.Exp_month}} <br>
                Expiration Year: {{default_credit_card.Exp_year}} <br>
                Last Four Digits: {{card_last_four}} <br>
                <a href="{% url 'prof:add_reserved_card' %}"> Click here to change default payment option</a>
            {% else %}
                No credit cards saved to account. <a href = "{% url 'prof:add_reserved_card' %}"> Click here to add one </a>
            {% endif %}
            <hr>
    
        {% else %} <!-- User not logged in -->
            <h2>Please register or login to make an order</h2>
            <a href = "{% url 'prof:register' %}"> Register </a> <br>        
            <a href = "{% url 'prof:login' %}"> Login </a>
        {% endif %}

        {% for item in items %}
        <h4>Item # {{forloop.counter}} </h4>
        Book Name: {{item.ISBN.Title}} <br>
        Book Cover:<br>
        <img src="{{item.ISBN.CoverImage.url}}" style="max-width:128px;max-height=128px"> <br>
        Price per: ${{item.ISBN.Price}} <br>
        Quantity: {{item.Quantity}} <br>
        {% endfor %}
        <hr>
    </div> <!-- Col -->
    <hr>

    <div class="col">
        <div class="col border border-info rounded shadow" style="min-height:150px;max-height:150px;max-width:300px;background-color:rgba(43, 213, 219, 0.295);margin-top:56px;margin-right:15px">
            Shipping: $0 <br>
            Tax: $0 <br><hr>
            Total: ${{subtotal}}<br>
            <a href="{% url 'myCart:confirm_checkout' %}" class="btn btn-warning" > <i class="fas fa-truck"></i> Checkout </a>
        </div>
    </div>
</div>


</div> <!-- row-->

{% endblock %}

Bookstore/templates/myCart/confirm_checkout.html
{% extends 'base.html' %}

{% block content %}

<div class= "container">
<h1> Order successful! </h1>
<h3> Your Order ID is : H4IK-EJIJ-4JJ4</h3>
<hr>
<a href="{% url 'homepage:index' %}"> Go to homepage</a>
</div>

{% endblock %}

Bookstore/templates/myCart/errorPage.html
<h1> Something went wrong</h1>

Bookstore/templates/myCart/example.html
{% extends 'myCart/base.html' %}

{% block content %}



eeqweqweqwe

<h1> Hello World</h1>
<buttom type="button" class="btn btn-warning">Click me!</buttom>

{% endblock %}

Bookstore/templates/myCart/index.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
 <br>
    <div class="container">
        <div class="jumbotron">
            <h1>Welcome! You're in the cart page</h1>
            <p>Below you'll find the items you've added to your cart.<br>
            Check the make sure everything's ok. Once you're done, click <br>
            'Complete Purchase(s)' to complete your transaction, 
            <strong>Thanks for using Geek Peeks!</strong>
        </div>
    </div>

    <div class="container">
        <div class="row col-md ">

            <!-- Item information --> <!-- Left side of the grid-->
            <div class="col">

                <!-- Cart content -->
                <h1> Shopping Cart </h1>
                <ul class="list-group"> 
                    {% if cart_content_list_length is 0 %}
                        <h4 style = "color:darkgray">Empty</h4>
                    {% endif %}

                    {% for item in cart_content_list %}
                    <li class="list-group-item" style = "background-color:#e9ecef;">  
			<div class="row">
			<div class="col">
                        	<h5> {{item.ISBN.Title}} </h5> 
				<h5> {{item.ISBN.ISBN}} </h5> 
				<div class="px-5 py-1">
                        	{% if item.ISBN.CoverImage == "book_images/noImage.png" or item.ISBN.CoverImage.url == 'None' or item.ISBN.CoverImage.url is None%} 
                        		<img src="{{item.ISBN.CoverImage.url}}" height="100" width="100">
                        	{% else %}
                        		<img src="{{item.ISBN.CoverImage.url}}" height="100" width="100">
                        	{% endif %}
				</div>
                        	<br>

			</div>
			<div class="col">
                        	<!-- <strong>Book_description: </strong> {{item.ISBN.Book_description}} <br> -->
				<h5 class="pt-3">Price: ${{item.ISBN.Price}}</h5> 

                        	<!-- Quantity-->                     
                        	<h5>Quantity: </h5>
                        	<form class="form-inline" action = "changeQuantity/" method="POST">
                            		{% csrf_token %}
                            		<input class ="form-control form-inline" style="width:50px" type="text" name = "New_quantity" value="{{item.Quantity}}">  
                            		<input type= "hidden" name="Cart_contentID" value = "{{item.Cart_contentID}}"> 
                            		<input type = "submit" class="btn btn-info" style="width:128px;" value="Update">

                        	</form>                         
                        	<br>
				<div class="row">

            			<div class="col">

                        	<!-- Remove from cart -->
                        	<form method = "POST" class = "form-inline" action="{% url 'myCart:removeCartItem' %}">
                            		{% csrf_token %}
                            		<input type = "hidden" name = "Cart_contentID" value="{{item.Cart_contentID}}">
                            		<input type = "submit" class = "btn btn-danger" style="min-width:128px;max-width:128px" value="Remove">                            
                        	</form>
				</div>

				<div class="col">

                        	<!-- Save for later-->
                        	{%if user.is_authenticated %}
                        	<form method = "POST" class = "form-inline" action="{% url 'myCart:moveCartItemToSFL' %}">
                        		{% csrf_token %}
                            		<input type = "hidden" name = "Cart_contentID" value="{{item.Cart_contentID}}">
                            		<input type = "submit" class = "btn btn-warning" style="width:128px;" value="Save for later">   
                        	</form>
                        	{% endif %}
				</div>
				</div>


			</div>
			</div>

                    
                    </li>
                    {% endfor %}
                </ul> <!-- List-Group for: Shopping Cart -->

                <br>
                    
                <!-- Saved for Later Content (Only displayed if user is logged in!) -->
                {% if user.is_authenticated %}
                <ul class="list-group"></ul>
                    <h1>Saved for later</h1>
                    {% if saved_for_later_content_list_length is 0 %}
                        <h4 style = "color:darkgray">Empty</h4>
                    {% endif %}
                    
                    {% for item in saved_for_later_content_list %}
                    <li class="list-group-item border-info">  
                    <strong>Book Title: {{item.ISBN.Title}} </strong> <br>
                    <strong>Book ISBN: </strong> {{item.ISBN.ISBN}} <br>
                    
                    <strong>Cover Image: </strong> <br> 
                    {% if item.ISBN.CoverImage == "book_images/noImage.png" or item.ISBN.CoverImage is None %} 
                    <img src="{{item.ISBN.CoverImage.url}}" height="100" width="100">
                    {% else %}
                    <img src="{{item.ISBN.CoverImage.url}}" height="100" width="100">
                    {% endif %}
                    
                    <br>
                    <!-- <strong>Book_description: </strong> {{item.ISBN.Book_description}} <br> -->
                    <strong>Price: $</strong>{{item.ISBN.Price}} <br>

                    <!-- Remove from Saved for later Button-->
                    <form method = "POST" class = "form-inline" action="{% url 'myCart:delete_SFL_item' %}">
                        {% csrf_token %}
                        <input type = "hidden" name = "Saved_ContentID" value="{{item.Saved_ContentID}}">
                        <input type = "submit" class = "btn btn-danger" style="width:128px" value="Delete">
                    </form>

                    <!-- Move to cart -->
                    <form method = "POST" class = "form-inline" action="{% url 'myCart:moveSflToCart' %}">
                        {% csrf_token %}
                        <input type = "hidden" name = "Saved_contentID" value="{{item.Saved_ContentID}}">
                        <input type = "submit" class = "btn btn-success" style="width:128px;" value="Move to cart">
                        </form>
                    </li>
                    {% endfor %} 
                </ul>
                {% endif %} <!-- is user authenticated -->
            </div> <!-- Column-->
            
            <!-- Subtotal Dialog Box --> <!-- This is the right side of the grid-->
            <div class="col border border-info rounded shadow" style="min-height:150px;max-height:150px;max-width:300px;background-color:rgba(43, 213, 219, 0.295);margin-top:56px;margin-right:15px">
                Subtotal: ${{subtotal}}<br>
                Shipping: FREE! <br>
                Tax: TAX FREE! <br><br>
                <!-- <a href="{% url 'myCart:checkout' %}" class="btn btn-warning" > <i class="fas fa-truck"></i> Make Order </a> -->
                <center><a class = "btn btn-info" href = "{% url 'myCart:checkout' %}" style = "width:90%"> <i class="fas fa-truck"></i> checkout </a> </center>
                <!-- <a class="btn btn-info" style="width:100%"><i class="fas fa-truck"></i> Checkout</button> -->
            </div>
            
        </div> <!-- Grid -->
    </div> <!-- Container-->
{% endblock %}

Bookstore/templates/myCart/savedforlaterinfo.html
<h1> TESTTTT</h1>

{% block ha %}
{% endblock %}