Bookstore/.w/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import Rate
from . import app_settings


urlpatterns = [
    url(r'(?P<content_type_id>\d+)/(?P<object_id>' + app_settings.STAR_RATINGS_OBJECT_ID_PATTERN + ')/', Rate.as_view(), name='rate'),
]

app_name = 'star_ratings'

Bookstore/Bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from myCart import urls
from homepage import urls
from BookDetails import urls
from products import urls

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', include('homepage.urls')),        
    path('myCart/', include('myCart.urls')),
    path('BookDetails/', include('BookDetails.urls')),
    path('homepage/', include('homepage.urls')),
    path('products/', include('products.urls')),
    path('prof/', include('prof.urls')),
    path('profile/', include('prof.urls'))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bookstore/prof/urls.py
from django.urls import path
from . import views

app_name = 'prof'
urlpatterns = [
    path ('profileInfo/', views.profileInfo, name = 'profileInfo'),
    path('register/', views.RegistrationView, name = 'register'),
    path('login/', views.user_login, name = 'login'),
    path('login/error/', views.user_login, name = 'login_error'),
    path('change_password/', views.change_password, name ="change_password"),
    path('logout/', views.user_logout, name = 'logout'),
    path('add_reserved_card/', views.add_reserved_card, name = "add_reserved_card"),
    path('add_preferred_card/', views.add_preferred_card, name = "add_preferred_card"),
    path('add_address/', views.add_shipping_address, name = "add_shipping_address"),
    path('modify_password/', views.modify_password, name ="modify_password")
]

Bookstore/prof/models.py
from django.db import models

# Create your models here.

Bookstore/prof/forms.py
from django import forms

class RegistrationForm(forms.Form):
    First_Name = forms.CharField(label = 'First Name', max_length= 100)
    Last_Name = forms.CharField(label = 'Last Name', max_length= 100)
    Username = forms.CharField(label='Username', max_length=100)
    Email = forms.EmailField(label ='Email')
    psw = forms.CharField(widget=forms.PasswordInput, label='Password')
    psw_repeat = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

class ChangePassword(forms.Form):
    old_psw = forms.CharField(widget=forms.PasswordInput, label='old_psw')
    psw = forms.CharField(widget=forms.PasswordInput, label='psw')
    psw_confirm = forms.CharField (widget=forms.PasswordInput, label='psw_confirm')

class LoginForm(forms.Form):
    Username = forms.CharField(label='Username', max_length=100)
    Password = forms.CharField(widget=forms.PasswordInput, label='Password')

class AddReservedCardForm(forms.Form):
    C_card_number = forms.CharField(max_length = 24)
    CVV = forms.CharField(max_length=8)
    Exp_month = forms.CharField(max_length=2)
    Exp_year = forms.CharField(max_length=4)
    Fname =  forms.CharField(max_length=32)
    Lname = forms.CharField(max_length=32)
    Mname = forms.CharField(max_length=32)

class AddUserAddress(forms.Form):
    Address_1 = forms.CharField(max_length=60)
    Address_2 = forms.CharField (max_length =60)
    City = forms.CharField(max_length=50)
    State = forms.CharField (max_length=50)
    Zip_Code = forms.IntegerField()
    Name = forms.CharField (max_length=50)
    Country = forms.CharField (max_length=50)

class AddPreferredCardForm(forms.Form):
    C_card_number = forms.CharField(max_length = 24)
    CVV = forms.CharField(max_length=8)
    Exp_month = forms.CharField(max_length=2)
    Exp_year = forms.CharField(max_length=4)
    Fname =  forms.CharField(max_length=32)
    Lname = forms.CharField(max_length=32)
    Mname = forms.CharField(max_length=32)

Bookstore/prof/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, reverse

from .forms import *
from database.models import USER, ADDRESS, USER_HOME_ADDRESS, CART, RESERVED_CREDIT_CARD, CREDIT_CARD, USER_SHIPPING_ADDRESS
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


from django.contrib.auth.models import User as AuthUser

from myCart import utility

def home (request):
    return render(request, "homepage/index.html", {})

def modify_password(request):
    return render (request, 'prof/modify_password.html')

def change_password(request):
    if request.method == "POST":
        form = ChangePassword (request.POST)

        if form.is_valid():
            psw = form.cleaned_data ["psw"]
            old_psw=form.cleaned_data["old_psw"]

            username=request.user.username

            user = authenticate(username=username, password=old_psw)

            if user is not None:
                user.set_password(psw)
                user.save()
                return HttpResponseRedirect(reverse('homepage:index'))

        else:
            return render(request, 'prof/modify_password.html', {})
    else:

        return render(request, 'prof/profileInfo.html', {})

def RegistrationView (request):
    
    if request.method =="POST":
        request.session
        #test
        print("WAS POST")
        form = RegistrationForm(request.POST)

        if form.is_valid():
            First_Name = request.POST.get('First_Name')
            Last_Name = request.POST.get('Last_Name')
            Username = request.POST.get('Username')
            Email = request.POST.get('Email', ' ')
            HomeAddress = request.POST.get('Address', ' ')
            City = request.POST.get('City', ' ')
            Zip_Code = request.POST.get('Zip_Code', ' ')
            psw = request.POST.get('psw')

            #Store Address
            print("creating Address...")
            HomeAddr = USER_HOME_ADDRESS()
            Addr = ADDRESS()
            Addr.Zip_Post = Zip_Code
            Addr.Address_1 = "" #fill this in later when user can fill this in a seperate form
            Addr.Address_2 = "" #fill this in later when user can fill this in a seperate form
            Addr.Country = "" #fill this in later when user can fill this in a seperate form
            Addr.State = "" #fill this in later when user can fill this in a seperate form
            Addr.City_Town = City
            Addr.Name = "" #fill this in later when user can fill this in a seperate form
            
            print("saving address...")
            Addr.save()
            HomeAddr.Address_ID = Addr
            HomeAddr.save()

            #Store AuthUser
            print("creating AuthUser")
            AuthUser_ID = AuthUser()
            AuthUser_ID.first_name = First_Name
            AuthUser_ID.last_name = Last_Name
            AuthUser_ID.email = Email
            AuthUser_ID.set_password(psw)
            AuthUser_ID.username = Username
            print("saving AuthUser...")
            AuthUser_ID.save() #if error occurs later on, username will still be saved in db! fix later
            
            print("creating USER...")
            #Store USER
            user_obj = USER()
            user_obj.AuthUser_ID = AuthUser_ID
            user_obj.Home_address_ID
            user_obj.Preferred_credit_card_ID = None

            cart = CART(Cart_ID = utility.generate_Cart_ID()) #for now!
            cart.save() #for now!
            user_obj.Cart_ID = cart #for now!

            user_obj.Nick_name = ''
            print("Saving user_obj....")
            user_obj.save()
            
            print("Sucess!:)")

            return HttpResponseRedirect(reverse('homepage:index'))
        else:
            #test
            print("Form was invalid!!!")
            print(form.errors)
    else:
        #test
        print("NOT POST")
        form = RegistrationForm()

    #return render (request, 'register.html', {'form': form,})
    return render (request, 'prof/register.html', {'form': form,})




def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["Username"]
            password = form.cleaned_data["Password"]

            user = authenticate(username=username, password=password)

            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('homepage:index')) 
                else:
                    HttpResponse("Uh oh, your account is currently not active! Send us an email so we can resolve the problem!")
            else:
                #raise Http404("Invalid password, please try again<br><a href='/'> Go back to homepage <a/>")
                return render (request, "prof/login_error.html")
        else:
            #form data was invalid. force user to reload page so he can try again
            return render(request, "prof/login.html")
    else:
        return render(request, "prof/login.html")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("homepage:index"))

@login_required
def profileInfo(request):    
    authUser = request.user
    user = authUser.user #taking advantage of one-to-one relationship. user is a USER object.

    #get all the reserved credit cards that point to the user
    reserved_credit_cards = user.reserved_credit_card_set.all()
    credit_cards = [] #will store all the credit cards that belong to the user.

    shipping_address = user.user_shipping_address_set.all()


    for rcc in reserved_credit_cards:
        print(str(rcc))
        credit_cards.append(rcc.C_card_number)

    print("----------------------------")
        
    for credit_card in credit_cards:
        print(str(credit_card) + " belongs to " + str(user.AuthUser_ID.username)) 

    print(type(user))

    #user is passed to get things like first name, lastname, username, etc.
    #credit cards is passed so we can view what credit cards he has added to his billing information
    context = {"userinfo":user, "credit_cards":credit_cards, "shipping_address":shipping_address}
    return render(request, "prof/profileInfo.html", context=context)

@login_required
def add_preferred_card(request):
    return None


@login_required
def add_reserved_card(request):
    
    if request.method == "POST":
        form = AddReservedCardForm(request.POST)
        
        if form.is_valid():
            print("form is valid!")
            C_card_number = form.cleaned_data["C_card_number"]
            CVV = form.cleaned_data["CVV"]
            Exp_month = form.cleaned_data["Exp_month"]
            Exp_year = form.cleaned_data["Exp_year"]
            Fname = form.cleaned_data["Fname"]
            Lname = form.cleaned_data["Lname"]
            Mname = form.cleaned_data["Mname"]

            credit_card = CREDIT_CARD(C_card_number=C_card_number)
            print("credit_card number is: " + str(credit_card))
            credit_card.CVV = CVV
            credit_card.Exp_month = Exp_month
            credit_card.Exp_year = Exp_year
            credit_card.Fname = Fname
            credit_card.Lname = Lname
            credit_card.Mname = Mname
            credit_card.save()
            
            authUser = request.user #AuthUser object
            print("authUser is: " + str(authUser))
            user = authUser.user #USER object
            print("user is: " + str(user))

            rcc = RESERVED_CREDIT_CARD()
            rcc.C_card_number = credit_card
            rcc.ProfileID = user
            rcc.save()

            return HttpResponseRedirect(reverse("prof:profileInfo"))
        else:
            print("Form is invalid")
            return render(request, "prof/add_reserved_card.html", context = {"form" : form})

    else:
        #Was not post, therefore show user a form to input reserved card info that the person wants to add to his account
        print("call was not POST")
        return render(request, "prof/add_reserved_card.html")
        
    return HttpResponse("Read CMD")

@login_required
def add_shipping_address (request):
    if request.method == "POST":
        form = AddUserAddress(request.POST)

        if form.is_valid():
            print("form is valid!")
            Address_1 = form.cleaned_data["Address_1"]
            Address_2 = form.cleaned_data["Address_2"]
            City = form.cleaned_data["City"]
            State = form.cleaned_data["State"]
            Zip_Code = form.cleaned_data["Zip_Code"]
            Country = form.cleaned_data ["Country"]
            Name = form.cleaned_data["Name"]

            address_shipping = ADDRESS()
            address_shipping.Address_1 = Address_1
            address_shipping.Address_2 = Address_2
            address_shipping.City_Town = City
            address_shipping.State = State
            address_shipping.Country = Country
            address_shipping.Zip_Post = Zip_Code
            address_shipping.Name = Name

            address_shipping.save()

            authUser = request.user  # AuthUser object
            print("authUser is: " + str(authUser))
            user = authUser.user  # USER object
            print("user is: " + str(user))

            usa = USER_SHIPPING_ADDRESS()
            usa.Address_ID = address_shipping
            usa.ProfileID = user
            usa.save()

            return HttpResponseRedirect(reverse("prof:profileInfo"))
        else:
            print("Form is invalid")
            return render(request, "prof/add_shipping_address.html", context={"form": form})

    else:
        # Was not post, therefore show user a form to input reserved card info that the person wants to add to his account
        print("call was not POST")

Bookstore/templates/prof/add_preferred_card.html
<!-- Not Yet Implemented -->

Bookstore/templates/prof/add_reserved_card.html
{% extends 'base.html' %}

{%  block additionalImports %}
<style>
    input[type=text]{
    width: 100%;
    padding: 15px;
    margin: 5px 0 15px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
}

input[type=text]:focus{
    background-color: #ddd;
    outline: none;
}

hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 25px;
}

</style>
{% endblock %}

{% block content %}
<div class="container">

    {{ form.errors }} <!-- Prints errors if there where any -->

    <form action= "{% url 'prof:add_reserved_card' %}" method = "POST" style="border:1px solid #ccc">
    
        {% csrf_token %}
        <h1>Billing Information</h1>
        <p> Please fill in this form to save your billing information.</p>
        <hr>
        <br/>
        <label for="Fname"><b>First Name </b></label>
        <input type="text" placeholder="John" name="Fname"  required>

        <label for="Mname"><b>Middle Name </b></label>
        <input type="text" placeholder="Don" name="Mname">

        <label for="Lname"><b>Last Name </b></label>
        <input type="text" placeholder="Doe" name="Lname"  required>

        <label for="C_card_number"><b>Credit card number </b></label>
        <input id="C_card_number" type="text" placeholder="1111-2222-3333-4444" name="C_card_number" required>

        <label for="Exp_month"><b>Exp Month</b></label>
            <select type="text" id = "Exp_month" placeholder="August" name="Exp_month" required>
                <option value="01">January</option>
                <option value="02">February</option>
                <option value="03">March</option>
                <option value="04">April</option>
                <option value="05">May</option>
                <option value="06">June</option>
                <option value="07">July</option>
                <option value="08">August</option>
                <option value="09">September</option>
                <option value="10">October</option>
                <option value="11">November</option>
                <option value="12">December</option>
            </select>

        <label for="Exp_year"><b>Exp Year</b></label>
            <select type="text" id = "Exp_year" placeholder="2018" name="Exp_year" required>
                <option value="2018">2018</option>
                <option value="2019">2019</option>
                <option value="2020">2020</option>
                <option value="2021">2021</option>
                <option value="2022">2022</option>
                <option value="2023">2023</option>
                <option value="2024">2024</option>
                <option value="2025">2025</option>
                <option value="2026">2026</option>
            </select>
        <br/>

        <label for="CVV"><b>CVV</b></label>
        <input type="text" id = "CVV" placeholder="1234" name="CVV">

        <div class="clearfix">
        <button type="submit" class="signupbtn btn btn-success">Add Card</button>
        </div>
    
    </form>

</div> <!-- container -->
{% endblock %}

Bookstore/templates/prof/add_shipping_address.html
{% extends 'base.html' %}

{%  block additionalImports %}
<style>
    input[type=text]{
    width: 100%;
    padding: 5px;
    margin: 5px 0 5px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
}

input[type=text]:focus{
    background-color: #ddd;
    outline: none;
}

hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 15px;
}

</style>
{% endblock %}

{% block content %}
<div class="container">

    {{ form.errors }} <!-- Prints errors if there where any -->

    <form action= "{% url 'prof:add_shipping_address' %}" method = "POST" style="border:1px solid #ccc">
    
        {% csrf_token %}
        <h1 style ='font-weight: bold;'>Shipping Information</h1>
        <p> Please fill in this form to save your shipping information.</p>
        <hr>
        <br/>
        <label for="Address_1"><b>Address 1 </b></label>
        <input type="text" placeholder="Address 1" name="Address_1"  required>

        <label for="Address_2"><b>Address 2 </b></label>
        <input type="text" placeholder="Address 2" name="Address_2">

        <label for="City"><b>City Town </b></label>
        <input type="text" placeholder="City" name="City"  required>

        <label for="State"><b>State </b></label>
        <input type="text" placeholder="State" name="State"  required>

        <label for="Zip_Code"><b>Zip Code </b></label>
        <input type="number" placeholder="11111" name="Zip_Code"  required>

        <label for="Country"><b>Country </b></label>
        <input type="text" placeholder="Country" name="Country"  required>

        <label for="Name"><b>Name </b></label>
        <input type="text" placeholder="House" name="Name">


        <br/>

        <div class="clearfix">
        <button type="submit" class="signupbtn btn btn-success">Add </button>
        </div>
    
    </form>

</div> <!-- container -->
{% endblock %}

Bookstore/templates/prof/login.html
{% load staticfiles %}
{% block additionalImports %}
<!-- Bootstrap core CSS -->
<link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Custom styles for this template -->  
<link href="jumbotron.css" rel="stylesheet">

<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<style>
    input[type=text], input[type=password] {
    width: 100%;
    padding: 15px;
    margin: 5px 0 15px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
    background-color: #ddd;
    outline: none;
}

hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 25px;
}
</style>
{% endblock %} <!-- additional imports endblock-->

{% block content %}
<form method = "POST" action="{% url 'prof:login' %}" style="border:1px solid #ccc">
<div class="container">
    {% csrf_token %}
    <h1>Sign In</h1>
    <hr>

    <label for="Username"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="Username" required>
    <label for="Password"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="Password" required>

    <input type = "submit" class = "btn btn-success" value="Sign in">
    <a type="button" href="/" class="btn btn-outline-danger my-0 my-sm-1">Cancel</a>
    <p  align="right"><a href="{% url 'prof:register' %}" style="color:dodgerblue">Don't have an account? Click here to create one!</a></p>
  </div>
</form>
{% endblock %}

Bookstore/templates/prof/login_error.html
{% load staticfiles %}
{% block additionalImports %}
<!-- Bootstrap core CSS -->
<link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Custom styles for this template -->  
<link href="jumbotron.css" rel="stylesheet">

<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<style>
    input[type=text], input[type=password] {
    width: 100%;
    padding: 15px;
    margin: 5px 0 15px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
    background-color: #ddd;
    outline: none;
}

hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 25px;
}
</style>
{% endblock %} <!-- additional imports endblock-->

{% block content %}
<form method = "POST" action="{% url 'prof:login_error' %}" style="border:1px solid #ccc">
<div class="container">
    {% csrf_token %}
    <h1>Sign In</h1>
    <hr>
    <p style="color:red;">Invalid Username or Password, please try again</p>

    <label for="Username"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="Username" required>
    <label for="Password"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="Password" required>

    <input type = "submit" class = "btn btn-success" value="Sign in">
    <a type="button" href="/" class="btn btn-outline-danger my-0 my-sm-1">Cancel</a>
    <p  align="right"><a href="{% url 'prof:register' %}" style="color:dodgerblue">Don't have an account? Click here to create one!</a></p>
  </div>
</form>
{% endblock %}

Bookstore/templates/prof/modify_password.html
{% load staticfiles %}
{% block additionalImports %}
<!-- Bootstrap core CSS -->
<link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="jumbotron.css" rel="stylesheet">

<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<style>
    input[type=text], input[type=password] {
    width: 100%;
    padding: 15px;
    margin: 5px 0 15px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
    background-color: #ddd;
    outline: none;
}

hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 25px;
}
</style>
{% endblock %} <!-- additional imports endblock-->

{% block content %}
<form method = "POST" action="{% url 'prof:change_password' %}" style="border:1px solid #ccc">
<div class="container">
    {% csrf_token %}
    <h1>Modify Password</h1>
    <hr>

    <label for="old_psw"><b>Old Password</b></label>
    <input type="password" placeholder="Enter Old Password" name="old_psw" required>
    <label for="psw"><b>New Password</b></label>
    <input type="password" placeholder="Enter new password" name="psw" required>
    <label for="psw_confirm"><b>Confirm New Password</b></label>
    <input type="password" placeholder="Enter New Password Again" name="psw_confirm" required>

    <input type = "submit" class = "btn btn-success" value="Save">
    <a type="button" href="/" class="btn btn-outline-danger my-0 my-sm-1">Cancel</a>

  </div>
</form>
{% endblock %}

Bookstore/templates/prof/profileInfo.html
{% extends 'base.html' %}

{%  block additionalImports %}
{% endblock %}



{% block content %}
<div class="container">
    <h1>Profile Information:</h1>

    <div class="card">
        <img src="/media/profile_images/img_avatar.png" alt="Avatar" style="width: 20%">
    </div>
    
    <p> First Name: {{ userinfo.AuthUser_ID.first_name }}<br>
        Last Name: {{ userinfo.AuthUser_ID.last_name }}<br>
        Username: {{ userinfo.AuthUser_ID.username }}</p>

    <form action="{% url 'prof:modify_password' %}">
        <input type="submit" class="btn btn-group" value="Change Password"/>
    </form>

    <p> ProfileID: {{ userinfo.ProfileID }} <br>
        CartID: {{ userinfo.Cart_ID }} </p>
    <hr>
    
    <h3> Billing Information</h3>
    {% for cc  in credit_cards %}
        <h5>Credit Card #{{ forloop.counter }}</h5>
        First Name: {{cc.Fname}} <br>
        Last Name: {{cc.Lname}} <br>
        Exp Year: {{cc.Exp_year}} <br>
        Exp Month: {{cc.Exp_month}} <br>


    {% endfor %}

    <br/>
    
    <form action="{% url 'prof:add_reserved_card' %}">
        <input type="submit" class="btn btn-success" value="Add a credit card" />
    </form>


<h3> Shipping Information</h3>
    {% for usa  in shipping_address %}
        <h5>Shipping #{{ forloop.counter }}</h5>
        Address 1: {{usa.Address_ID.Address_1}} <br>
        Address 2: {{usa.Address_ID.Addess_2}} <br>
        City: {{usa.Address_ID.City_Town}} <br>
        State: {{usa.Address_ID.State}} <br>
        Zip Code: {{usa.Address_ID.Zip_Post}} <br>
        Country: {{usa.Address_ID.Country}} <br>
        Name: {{usa.Address_ID.Name}} <br>


    {% endfor %}

    <form action="{% url 'prof:add_shipping_address' %}">
        <input type="submit" class="btn btn-success" value="Add a shipping address" />
    </form>

</div> 
{% endblock %}

Bookstore/templates/prof/register.html
{% load staticfiles %}

<!DOCTYPE html>
<head>
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">   
</head>
<html lang="en">
<style>
    input[type=text], input[type=password], input[type=email], input[type=number] {
    width: 100%;
    padding: 15px;
    margin: 5px 0 15px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
    background-color: #ddd;
    outline: none;
}

hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 25px;
}

</style>
<!-- <form action="/register/" method = "POST" style="border:1px solid #ccc"> -->

<form action="{% url 'prof:register' %}" method = "POST" style="border:1px solid #ccc">  
    {% csrf_token %}
    {{ form.title.errors }}
    {{ form.title }}
    <div class="container">
    <h1>Sign Up</h1>
    <p> Please fill in this form to create an account.</p>
    <hr>

    <label for="First_Name"><b>First Name</b></label>
    <!--<input type="text" placeholder="Enter First Name" name="first_name"  required> -->
    <input type="text" placeholder="Enter First Name" name="First_Name"  required>

    <label for="Last_Name"><b>Last Name</b></label>
    <!--<input type="text" placeholder="Enter Last Name" name="last_name"  required> -->
    <input type="text" placeholder="Enter Last Name" name="Last_Name"  required>

    <label for="Username"><b>Username</b></label>
    <!--<input id="Username" type="text" placeholder="Enter Username" name="username" value = "{{ current_username }}" required>-->
    <input id="Username" type="text" placeholder="Enter Username" name="Username" value = "{{ current_username }}" required>

    <label for="Email"><b>Email</b></label>
    <!-- <input type="email" placeholder="Enter Email" name="email" required> -->
    <input type="email" placeholder="Enter Email" name="Email" required>

    <label for="psw"><b>Password</b></label>    
    <input type="password" placeholder="Enter Password" name="psw" required>

    <label for="psw_repeat"><b>Confirm Password</b></label>
    <input type="password" placeholder="Confirm Password" name="psw_repeat" required>

    <p align="left">By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>
    <div class="clearfix">
      <button class="btn btn-outline-primary btn-lg btn-block my-2 my-sm-1" type="submit">Sign up</button>
      <a class="btn btn-outline-danger btn-lg btn-block my-2 my-sm-1" href="/" type="submit">Cancel</a>      
    </div>  
  </div> <!--Container-->
</form>

</html>