Bookstore/.w/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import Rate
from . import app_settings


urlpatterns = [
    url(r'(?P<content_type_id>\d+)/(?P<object_id>' + app_settings.STAR_RATINGS_OBJECT_ID_PATTERN + ')/', Rate.as_view(), name='rate'),
]

app_name = 'star_ratings'

Bookstore/Bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from myCart import urls
from homepage import urls
from BookDetails import urls
from products import urls

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', include('homepage.urls')),        
    path('myCart/', include('myCart.urls')),
    path('BookDetails/', include('BookDetails.urls')),
    path('homepage/', include('homepage.urls')),
    path('products/', include('products.urls')),
    path('prof/', include('prof.urls')),
    path('profile/', include('prof.urls'))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bookstore/myCart/urls.py
from django.urls import path
from . import views

app_name = "myCart"
urlpatterns = [
    path('', views.index, name='index'),
    path('myCart/', views.index, name="myCart"),
    path('changeQuantity/', views.cart_quantity_change, name="changeQuantity"),
    path('removeCartItem/', views.cart_item_remove, name = "removeCartItem"),
    path('deleteSFLitem/', views.delete_SFL_item, name = "delete_SFL_item"),
    path('moveCartItemToSFL/', views.move_cart_item_to_SFL, name = "moveCartItemToSFL"),
    path('moveSflToCart/', views.move_sfl_item_to_cart, name="moveSflToCart"),
    path('addItem/', views.add_item, name ="add_item"),
    path('checkout/', views.checkout, name = "checkout"),
    path('confirm_checkout/', views.confirm_checkout, name = "confirm_checkout"),



    #Views for TESTING. IGNORE THESE
    path('createCookieTest/', views.createCookieTest, name="createCookieTest"),
    path('cookieInfo/', views.cookieInfo, name='cookieInfo'),
    path('makeCartCookie/', views.makeCartCookie, name='makeCartCookie'),
    #path('login_page/', views.login_page, name="loginpage"),
    path('homepage/', views.homepage, name="homepage"),
    path('testView1/', views.testView1, name="testView1"),
    path('sessionTest/', views.sessionTest, name="sessionTest"),
    #path('index', views.index2, name = 'index2')
]

Bookstore/prof/urls.py
from django.urls import path
from . import views

app_name = 'prof'
urlpatterns = [
    path ('profileInfo/', views.profileInfo, name = 'profileInfo'),
    path('register/', views.RegistrationView, name = 'register'),
    path('login/', views.user_login, name = 'login'),
    path('login/error/', views.user_login, name = 'login_error'),
    path('change_password/', views.change_password, name ="change_password"),
    path('logout/', views.user_logout, name = 'logout'),
    path('add_reserved_card/', views.add_reserved_card, name = "add_reserved_card"),
    path('add_preferred_card/', views.add_preferred_card, name = "add_preferred_card"),
    path('add_address/', views.add_shipping_address, name = "add_shipping_address"),
    path('modify_password/', views.modify_password, name ="modify_password")
]

Bookstore/templates/base.html
{% load static %} 
<!doctype html>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->    
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> 

    <!-- Add any additional imports that you would like in this block-->
    {% block additionalImports %}
    
    {% endblock %}

    <!-- Glyphicons by fontawesome.com -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <title>Geek Peek</title>
  </head>
  <body>      
   
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

            <!-- Brand -->
            <a class="navbar-brand" href="/">
                <img class="rounded-circle" src= "{% static "images/TemporaryLogo.jpg" %}" width="30" height="30" class="d-inline-block align-top" alt="">    
                Geek Peek
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                
                <!-- Home link -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>                   
                </ul>

                <!-- Login/Register/Admin Button-->
                {% if user.is_authenticated %}
                    <span class="navbar-text mr-sm-2">
                        Hello, {{user.username}}
                    </span>
                {% else %}
                    <div class="btn-group m-sm-2">
                        <a href="{% url 'prof:register' %}" class="btn btn-primary">Sign Up</a>
                        <a href="{% url 'prof:login' %}" class="btn btn-primary">Login</a>     
                        <a href="/admin/" class = "btn btn-info"> Admin</a>
                    </div>
                {% endif %}
                
                <!-- Cart Button -->
                <a href="{% url 'myCart:index' %}" class="btn btn-warning mr-sm-2">
                    <i class = "fa fa-shopping-cart"></i>
                    View Cart
                    <span class="badge" style="font-size:100%"></span> <!-- Static for now --> 
                </a>
                
                <!--Search Bar-->
                <form class="form-inline my-3 my-lg-0"> 
                    <input class="form-control mr-sm-2" type="search" placeholder="Book Search" aria-label="Search">
                    <button class="btn btn-success my-2 my-sm-0 mr-sm-1" type="submit">Search</button>
                </form>

                 <!--View Profile-->
                {% if user.is_authenticated %}
                <a href="{% url 'prof:profileInfo' %}" class="btn btn-primary mr-sm-1"> View Profile </a>
                {% endif %} 

                <!-- Logout button (if user loged in)-->
                {% if user.is_authenticated %}
                <span class="navbar-text mr-sm-2">
                    <a href = "{% url 'prof:logout' %}" class = "btn btn-danger"> Log Out</a>
                </span>
                {% endif %}

            </div> <!--Collapse-->
        </nav> <!--Navigation bar-->
    
    
    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>