Bookstore/.w/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import Rate
from . import app_settings


urlpatterns = [
    url(r'(?P<content_type_id>\d+)/(?P<object_id>' + app_settings.STAR_RATINGS_OBJECT_ID_PATTERN + ')/', Rate.as_view(), name='rate'),
]

app_name = 'star_ratings'

Bookstore/BookDetails/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name ='index'),
        path('BooksByAuthor/', views.books_by_author, name ='BooksByAuthor'),

]

Bookstore/Bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from myCart import urls
from homepage import urls
from BookDetails import urls
from products import urls

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', include('homepage.urls')),        
    path('myCart/', include('myCart.urls')),
    path('BookDetails/', include('BookDetails.urls')),
    path('homepage/', include('homepage.urls')),
    path('products/', include('products.urls')),
    path('prof/', include('prof.urls')),
    path('profile/', include('prof.urls'))
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bookstore/myCart/urls.py
from django.urls import path
from . import views

app_name = "myCart"
urlpatterns = [
    path('', views.index, name='index'),
    path('myCart/', views.index, name="myCart"),
    path('changeQuantity/', views.cart_quantity_change, name="changeQuantity"),
    path('removeCartItem/', views.cart_item_remove, name = "removeCartItem"),
    path('deleteSFLitem/', views.delete_SFL_item, name = "delete_SFL_item"),
    path('moveCartItemToSFL/', views.move_cart_item_to_SFL, name = "moveCartItemToSFL"),
    path('moveSflToCart/', views.move_sfl_item_to_cart, name="moveSflToCart"),
    path('addItem/', views.add_item, name ="add_item"),
    path('checkout/', views.checkout, name = "checkout"),
    path('confirm_checkout/', views.confirm_checkout, name = "confirm_checkout"),



    #Views for TESTING. IGNORE THESE
    path('createCookieTest/', views.createCookieTest, name="createCookieTest"),
    path('cookieInfo/', views.cookieInfo, name='cookieInfo'),
    path('makeCartCookie/', views.makeCartCookie, name='makeCartCookie'),
    #path('login_page/', views.login_page, name="loginpage"),
    path('homepage/', views.homepage, name="homepage"),
    path('testView1/', views.testView1, name="testView1"),
    path('sessionTest/', views.sessionTest, name="sessionTest"),
    #path('index', views.index2, name = 'index2')
]

Bookstore/BookDetails/models.py
from django.db import models

# Create your models here.

Bookstore/BookDetails/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.template import loader
from database.models import BOOK, COMMENT, BOOK_RATING, AUTHOR



# Given a BOOK object, returns a "Book Details" page.
def index(request):
    
    template = loader.get_template('BookDetails/book_details.html')
    if request.method=='GET':
        book = request.GET.get('book')
    if not book:
        book = "9780261103283"
    

    book = BOOK.objects.get(ISBN=str(book))
    comments = COMMENT.objects.filter(ISBN = book)

    rating = BOOK_RATING.objects.get(ISBN = book)
    
    # Taking an average of the ratings values stored 
    # in the database for the given BOOK object. 
    total_ratings = (rating.One_star_count + rating.Two_star_count + rating.Three_star_count + rating.Four_star_count + rating.Five_star_count)
    
    # Avoiding divide by zero issue
    # Integer division behavior
    if not total_ratings == 0:
        average_rating = ((rating.One_star_count * 1 ) + (rating.Two_star_count * 2 ) + (rating.Three_star_count * 3 ) + (rating.Four_star_count * 4 ) + (rating.Five_star_count * 5 )) / total_ratings
        average_rating = round(average_rating) 
    else:
        average_rating = 0

    

    # If no book found, set book found render an error
    context = { 'book':book, 'comments':comments, 'rating':average_rating, 'range': range(average_rating), 'n_filled_range': range(5 - average_rating) }
    

    return HttpResponse(template.render(context, request))


# Given an AUTHOR object returns "Books By Author" page.
def books_by_author(request):

    template = loader.get_template('BookDetails/books_by_author.html')
    author = None
    if request.method=='GET':
        author = request.GET.get('author')
        author = AUTHOR.objects.get(AuthorID=author)

    books = BOOK.objects.filter(AuthorID = author)
    context = { 'author':author, 'books':books, }
    
    return HttpResponse(template.render(context, request))

Bookstore/templates/BookDetails/book_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block additionalImports %}

<!-- Styles for this template -->

<link href="{% static 'css/comment.css' %}" media="all" rel="stylesheet" type="text/css" />
<link href="{% static 'css/modal.css' %}" rel="stylesheet"> 
<link rel="stylesheet" href="https://lokeshdhakar.com/projects/lightbox2/css/lightbox.css">
<link rel="stylesheet" href="{% static 'css/star-ratings.css' %}">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">



<!-- Jvascript code -->

<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> 
<script src="{% static 'lightbox/src/js/lightbox.js' %}"></script>

<!-- Switches Nav tabs -->
<script>
	$(document).ready(function(){
		$(".nav-tabs a").click(function(){
			$(this).tab('show');
		});
	});
</script>

<!-- Unpacking dictionary -->
<script>
	<% for key, value in context.items %>	
		<%if key == 'book'%>
			# Obtaining BOOK object
			<% book = value %>
		<%if key == 'comments' %>
			# Obtaining COMMENT objects related to the book
			<%comments = value%>
		<%if key == 'n_filled_range'%>
			# Obtaining a range of unfilled stars to draw
			# domain = subset of {0, 1, 2, 3, 4, 5}
			<%n_filled_range = value%>
		<%if key == 'rating'%>
			# domain = {0, 1, 2, 3, 4, 5}
			<%rating = value%>
		<%if key == 'range'%>
			# Obtaining a range of filled stars to draw
			# domain = subset of {0, 1, 2, 3, 4, 5}
			<%range = value%>
	<% endfor %>
</script>

{% endblock %}
{% block content %}

<div class="container  col-md-10">

	<h1 class="text-left">{{ book.Title }}</h1>
	<br></br>
</div>
<div class="container  col-md-7">

	<a class="example-image-link" href="{{book.CoverImage.url}}" data-lightbox="example-1" >
		<center>
			<img  class="example-image img-thumbnail img-fluid" style="max-width:300px" alt="image-1" src="{{book.CoverImage.url}}"/>
		</center>
	</a>


	<br></br>

	<hr>
	<div class="row">
		<div class="col py-5 px-5 text-center">

			<h4>${{ book.Price }}</h4>
			<br>
			<form method="POST" action="{% url 'myCart:add_item' %}">
				{% csrf_token %}
				<input type= "hidden" name="ISBN" value = "{{book.ISBN}}">
				<input type = "submit" class="btn btn-info" style="width:150px;" value="Add to cart">
			</form>
		</div>

		<div class="float-right text-center col py-5 px-5">

			<div >

				<h4>{{rating}} Star(s)</h4>		
				<div class="starrating risingstar d-flex justify-content-center flex-row-reverse">

					<!-- Drawing any unfilled stars first-->
					{% for i in n_filled_range %}
					<input type="radio" id="star{{i|add:rating}}" name="rating" value="{{i|add:rating}}" /><label for="star{{i|add:rating}}" title="{{i|add:rating}} star"></label>
					{% endfor %}

					<!-- Drawing any filled stars -->
					{% for i in range %}
					<input type="radio" id="star{{i|add:"1"}}" name="rating" value="{{i|add:"1"}}" /><label style="color: #ffca08" for="star{{i|add:"1"}}" title="{{i|add:"1"}} star"></label>
					{% endfor %}

				</div>
			</div>    
		</div>
	</div>



	<hr>

	<br></br>


	<div >		

		<!-- Nav tabs to toggle between the book summary, details, and comments --> 
		<ul class="nav nav-tabs">

			<li><a href="#description" class="btn btn-secondary active btn-group" role="button">Summary</a></li>
			<li><a href="#details"  class="btn btn-secondary btn-group" role="button">Details</a></li>
			<li><a href="#comments" class="btn btn-secondary btn-group" role="button" >Comments</a></li>
		</ul>
		<div class="panel-body tab-content border px-2 pt-3">
			<!-- Retrieving description from book object -->
			<div class="tab-pane in active col-lg" id="description">
				<h2>Summary:</h2>
				<hr>
				<p>		
					{{ book.Book_description|safe }}	
				</p>

			</div>

			<!-- Retrieving book details -->
			<div class="tab-pane fade col-lg" id="details">
				<h2>Details:</h2>
				<hr>
				<div class="col-sm px-5">
					<table class="table table-striped">
						<tr>
							<td><strong>Title:</strong></td>  
							<td>{{ book.Title }}</td>
						</tr>
						<tr>
							<td ><strong>Author:</strong></td>
							<td> <a class="btn-link" href="/BookDetails/BooksByAuthor/?author={{ book.AuthorID.AuthorID }}">{{book.AuthorID.Fname}} {{book.AuthorID.Lname}}</a></td>
						</tr>
						<tr>
							<td><strong>ISBN:</strong></td>
							<td>{{ book.ISBN }}</td>
						</tr>
						<tr>
							<td><strong>Genre:</strong></td>
							<td>{{ book.GenreID.Name }}</td>
						</tr>
						<tr>
							<td><strong>Publisher:</strong></td>
							<td>{{ book.PublisherID.Name }}</td>
						</tr>
						<tr>
							<td><strong>Release Date:</strong></td>
							<td>{{ book.Release_date }}</td>
						</tr>
					</table>
				</div>

			</div>
			<!-- Retrieving book comments -->
			<div class="tab-pane fade col-lg" id="comments">
				<h2>Comments:</h2>

				{%for comment in comments%}	
					<hr>
					<div class="comment">
						<div class="comment-author">{{ comment.ProfileID.AuthUser_ID }}</div>
						<div class="comment-text">
							{{ comment.Comment_Text }}
							<div class="comment-date">{{ comment.Time_posted}}</div>
						</div>
					</div>
				{% endfor %}

			</div>
		</div>

	</div>
	
	<!-- Expandable *About the author* link -->
	<div class="container float-left text-left">	
		<br></br>
		<br></br>
		<div class="panel-group">
			<div class="panel panel-default">
				<div class="panel-heading">
					<a data-toggle="collapse" href="#collapse1"><h4 class="panel-title">About the author...</h4></a>
				</div>

				<div id="collapse1" class="panel-collapse collapse col-lg">
					<!-- Retrieving book's author name and biography -->
					<div class="panel-body">
						<br></br>
						<a class="btn-link" href="/BookDetails/BooksByAuthor/?author={{ book.AuthorID.AuthorID }}"><h5>{{book.AuthorID.Fname}} {{book.AuthorID.Lname}}</h5></a>
						<br>
						<div class="mx-5 px-5 comment-text">
							{{book.AuthorID.Bio}}
						</div>
					</div>
				</div>
			</div>
		</div>

		<br></br>
		<br></br>
		<br></br>
	</div>	

</div>


{% endblock %}

Bookstore/templates/BookDetails/books_by_author.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block additionalImports %}
<!-- Custom styles for this template -->

<!-- Using Comment styling for books and details -->
<link href="{% static 'css/comment.css' %}" media="all" rel="stylesheet" type="text/css" />


<!-- Unpacking Author object and Books they wrote -->
<script>
	<% for key, value in context.items %>	
	<%if key == 'books'%>
	<!-- Obtaining BOOK objects -->
	<% books = value %>
	<%if key == 'author'%>
	<!-- Obtaining Author Object -->
	<%author = value%>
	<% endfor %>
</script>



{% endblock %}
{% block content %}
<!-- Retrieving Author's name to display in page header -->
<div class="container col-md-10">

	<br></br>
	<h1 class="text-left">Books by {{ author.Fname }} {{ author.Lname }}</h1>
</div>
<div class="container col-md-7">
	<br></br>
	<div id="comments">

		<!-- Loops through each book in the database written by the specified author -->
		{% for book in books %}	
		<!-- Using the Comment style for each of the books -->
		<div class="comment px-3 py-3">
			<div class="comment-author"><h2>  <a class="btn-link" href="/BookDetails/?book={{ book.ISBN }}">{{book.Title}}</a></h2></div>
			<div class="comment-text">
				<div class="row">
					<div class="col-4">
						<center>
							<a class="btn-link" href="/BookDetails/?book={{book.ISBN}}">
								<img  class="mt-5  example-image img-thumbnail img-fluid" style="max-width:200px;" alt="image-1" src="{{book.CoverImage.url}}"/>
							</a>
						</center>
					</div>
					<div class="col ">
						<br></br>
						<div class="px-4 py-3">
							<table class="table table-striped">
								<tr>
									<td><strong>Title:</strong></td>
									<td>{{ book.Title }}</td>
								</tr>
								<tr>
									<td ><strong>Author:</strong></td>
									<td>{{book.AuthorID.Fname}} {{book.AuthorID.Lname}}</td>
								</tr>
								<tr>
									<td><strong>ISBN:</strong></td>
									<td>{{ book.ISBN }}</td>
								</tr>
								<tr>
									<td><strong>Genre:</strong></td>
									<td>{{ book.GenreID.Name }}</td>
								</tr>
								<tr>
									<td><strong>Publisher:</strong></td>
									<td>{{ book.PublisherID.Name }}</td>
								</tr>
								<tr>
									<td><strong>Release Date:</strong></td>
									<td>{{ book.Release_date }}</td>
								</tr>
							</table>

						</div>

					</div>
				</div>
			</div>

		</div>
		<br>
		{% endfor %}
	</div>

</div>
{% endblock %}